import "driver.js/dist/driver.css";
import "./globals.css";
import Activator from "./tutorial/TutorialToggle";

export const metadata = {
  title: "Maple Nest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" relative">
        <div className=" h-screen entire_content">
          {children}
        </div>
      </body>
    </html>
  );
}
